### ISSUE TITLE
pet-shop checklist

### ISSUE THREAD

**Issue by viniciussm07** [viniciussm07/pet-shop#1]
- [x] setup projeto Next.js
- [x] #4
- [ ] #5
- [ ] #6
- [x] https://github.com/viniciussm07/pet-shop/issues/3
- [ ] https://github.com/viniciussm07/pet-shop/issues/2
